[package]
name = "holder"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
rand = "0.8"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0.140"
tokio = { version = "1", features = ["full"] }
